export type { IUser } from '@src/modules/Users/domain/Entity/IUser';
export type { IOrganization } from '@src/modules/Users/domain/Entity/IOrganization';
export { User } from '@src/modules/Users/domain/Model/User';
export { Organization } from '@src/modules/Users/domain/Model/Organization';
export { UserDataRepository } from '@src/modules/Users/adapters/out/persistence/UserDataRepository';
export { OrganizationDataRepository } from '@src/modules/Users/adapters/out/persistence/OrganizationDataRepository';
export { UserService } from '@src/modules/Users/service/UserService';
export { OrganizationService } from '@src/modules/Users/service/OrganizationService';
export { composeUsersAuthServices } from '@src/modules/Users/composition/composeUsersAuthServices';
export { UserUseCases } from '@src/modules/Users/application/use-cases/UserUseCases';
export { OrganizationUseCases } from '@src/modules/Users/application/use-cases/OrganizationUseCases';
export { AuthUseCases } from '@src/modules/Users/application/use-cases/AuthUseCases';

export { UserController } from '@src/modules/Users/adapters/in/http/controllers/UserController';
export { AuthController } from '@src/modules/Users/adapters/in/http/controllers/AuthController';
export { OrganizationController } from '@src/modules/Users/adapters/in/http/controllers/OrganizationController';
export { UserController as UserHttpController } from '@src/modules/Users/adapters/in/http/controllers/UserController';
export { AuthController as AuthHttpController } from '@src/modules/Users/adapters/in/http/controllers/AuthController';
export { OrganizationController as OrganizationHttpController } from '@src/modules/Users/adapters/in/http/controllers/OrganizationController';
export { AuthService } from '@src/modules/Users/service/AuthService';
export { UserProviderLocal } from '@src/modules/Users/service/UserProviderLocal';

// dtos
export type { RequestCreateDocument } from '@src/modules/Users/interface/dto/RequestCreateDocument';
export type { RequestCreateAddress } from '@src/modules/Users/interface/dto/RequestCreateAddress';
export type { RequestCreateEmail } from '@src/modules/Users/interface/dto/RequestCreateEmail';
export type { RequestCreatePhone } from '@src/modules/Users/interface/dto/RequestCreatePhone';
export type { RequestCreateUser } from '@src/modules/Users/interface/dto/RequestCreateUser';
export type { RequestCreateOrganization } from '@src/modules/Users/interface/dto/RequestCreateOrganization';
export type { RequestUpdateDocument } from '@src/modules/Users/interface/dto/RequestUpdateDocument';
export type { RequestUpdateAddress } from '@src/modules/Users/interface/dto/RequestUpdateAddress';
export type { RequestUpdateEmail } from '@src/modules/Users/interface/dto/RequestUpdateEmail';
export type { RequestUpdatePassword } from '@src/modules/Users/interface/dto/RequestUpdatePassword';
export type { RequestUpdatePhone } from '@src/modules/Users/interface/dto/RequestUpdatePhone';
export type { RequestUpdateUser } from '@src/modules/Users/interface/dto/RequestUpdateUser';
export type { RequestUpdateOrganization } from '@src/modules/Users/interface/dto/RequestUpdateOrganization';

export type { ILoginRequest } from '@src/modules/Users/interface/dto/ILoginRequest';
export type { ILogoutRequest } from '@src/modules/Users/interface/dto/ILogoutRequest';
export type { IRegisterRequest } from '@src/modules/Users/interface/dto/IRegisterRequest';
export type { IUpdatePasswordRequest } from '@src/modules/Users/interface/dto/IUpdatePasswordRequest';

export { getAllUsers } from '@src/modules/Users/features/getAllUsers';
export { createUser } from '@src/modules/Users/features/createUser';
export { updateUser } from '@src/modules/Users/features/updateUser';
export { getUserById } from '@src/modules/Users/features/getUserById';
export { deleteUserById } from '@src/modules/Users/features/deleteUserById';
export { updatePassword } from '@src/modules/Users/features/updatePassword';
export { createDocument } from '@src/modules/Users/features/createDocument';
export { updateDocument } from '@src/modules/Users/features/updateDocument';
export { deleteDocument } from '@src/modules/Users/features/deleteDocument';
export { createPhone } from '@src/modules/Users/features/createPhone';
export { updatePhone } from '@src/modules/Users/features/updatePhone';
export { deletePhone } from '@src/modules/Users/features/deletePhone';
export { createEmail } from '@src/modules/Users/features/createEmail';
export { updateEmail } from '@src/modules/Users/features/updateEmail';
export { deleteEmail } from '@src/modules/Users/features/deleteEmail';

export type { IAuthService } from '@src/modules/Users/service/ports/IAuthService';
export type { IAuthSchema } from '@src/modules/Users/service/ports/IAuthSchema';
export { EAuthSchemaType } from '@src/modules/Users/service/ports/EAuthSchemaType';
export type { IUserProvider } from '@src/modules/Users/service/ports/IUserProvider';
export type { IUserRepository } from '@src/modules/Users/service/ports/IUserRepository';
export type { IOrganizationRepository } from '@src/modules/Users/service/ports/IOrganizationRepository';
export type { IAuthorizationHeader } from '@src/modules/Users/service/ports/IAuthorizationHeader';
export type { ITokenObject } from '@src/modules/Users/service/ports/ITokenObject';
export type { IUserUseCases } from '@src/modules/Users/application/ports/IUserUseCases';
export type { IOrganizationUseCases } from '@src/modules/Users/application/ports/IOrganizationUseCases';
export type { IAuthUseCases } from '@src/modules/Users/application/ports/IAuthUseCases';
export { UserUseCases as UserApplicationUseCases } from '@src/modules/Users/application/use-cases/UserUseCases';
export { OrganizationUseCases as OrganizationApplicationUseCases } from '@src/modules/Users/application/use-cases/OrganizationUseCases';
export { AuthUseCases as AuthApplicationUseCases } from '@src/modules/Users/application/use-cases/AuthUseCases';
export { EUserRole, ROLE_SCOPE_MATRIX } from '@src/modules/Users/domain/security/Rbac';

// events
export { UserCreateRequestEvent } from '@src/modules/Users/events/UserCreateRequestEvent';
export { UserDeleteRequestEvent } from '@src/modules/Users/events/UserDeleteRequestEvent';
export { UserDocumentCreateRequestEvent } from '@src/modules/Users/events/UserDocumentCreateRequestEvent';
export { UserDocumentDeleteRequestEvent } from '@src/modules/Users/events/UserDocumentDeleteRequestEvent';
export { UserDocumentUpdateRequestEvent } from '@src/modules/Users/events/UserDocumentUpdateRequestEvent';
export { UserEmailCreateRequestEvent } from '@src/modules/Users/events/UserEmailCreateRequestEvent';
export { UserEmailDeleteRequestEvent } from '@src/modules/Users/events/UserEmailDeleteRequestEvent';
export { UserEmailUpdateRequestEvent } from '@src/modules/Users/events/UserEmailUpdateRequestEvent';
export { UserGetAllRequestEvent } from '@src/modules/Users/events/UserGetAllRequestEvent';
export { UserGetOneRequestEvent } from '@src/modules/Users/events/UserGetOneRequestEvent';
export { UserPasswordUpdateRequestEvent } from '@src/modules/Users/events/UserPasswordUpdateRequestEvent';
export { UserPhoneCreateRequestEvent } from '@src/modules/Users/events/UserPhoneCreateRequestEvent';
export { UserPhoneDeleteRequestEvent } from '@src/modules/Users/events/UserPhoneDeleteRequestEvent';
export { UserPhoneUpdateRequestEvent } from '@src/modules/Users/events/UserPhoneUpdateRequestEvent';
export { UserUpdateRequestEvent } from '@src/modules/Users/events/UserUpdateRequestEvent';

export { LoginRequestEvent } from '@src/modules/Users/events/LoginRequestEvent';
export { LogoutRequestEvent } from '@src/modules/Users/events/LogoutRequestEvent';
export { RegisterRequestEvent } from '@src/modules/Users/events/RegisterRequestEvent';
export { UpdatePasswordRequestEvent } from '@src/modules/Users/events/UpdatePasswordRequestEvent';
export { OrganizationCreateRequestEvent } from '@src/modules/Users/events/OrganizationCreateRequestEvent';
export { OrganizationGetAllRequestEvent } from '@src/modules/Users/events/OrganizationGetAllRequestEvent';
export { OrganizationGetOneRequestEvent } from '@src/modules/Users/events/OrganizationGetOneRequestEvent';
export { OrganizationUpdateRequestEvent } from '@src/modules/Users/events/OrganizationUpdateRequestEvent';
export { OrganizationDeleteRequestEvent } from '@src/modules/Users/events/OrganizationDeleteRequestEvent';
export { OrganizationAddressCreateRequestEvent } from '@src/modules/Users/events/OrganizationAddressCreateRequestEvent';
export { OrganizationAddressUpdateRequestEvent } from '@src/modules/Users/events/OrganizationAddressUpdateRequestEvent';
export { OrganizationAddressDeleteRequestEvent } from '@src/modules/Users/events/OrganizationAddressDeleteRequestEvent';
export { OrganizationPhoneCreateRequestEvent } from '@src/modules/Users/events/OrganizationPhoneCreateRequestEvent';
export { OrganizationPhoneUpdateRequestEvent } from '@src/modules/Users/events/OrganizationPhoneUpdateRequestEvent';
export { OrganizationPhoneDeleteRequestEvent } from '@src/modules/Users/events/OrganizationPhoneDeleteRequestEvent';
export { OrganizationEmailCreateRequestEvent } from '@src/modules/Users/events/OrganizationEmailCreateRequestEvent';
export { OrganizationEmailUpdateRequestEvent } from '@src/modules/Users/events/OrganizationEmailUpdateRequestEvent';
export { OrganizationEmailDeleteRequestEvent } from '@src/modules/Users/events/OrganizationEmailDeleteRequestEvent';
export { UserIntegrationEventName } from '@src/modules/Users/events/contracts/UserIntegrationEventName';
export { UserMessageContracts } from '@src/modules/Users/events/contracts/UserMessageContracts';
export type { IUserEventListeners } from '@src/modules/Users/events/contracts/IUserEventListeners';
export { registerUserEventListeners } from '@src/modules/Users/events/listeners/registerUserEventListeners';
export { registerUserMessageHandlers } from '@src/modules/Users/events/listeners/registerUserMessageHandlers';
