sonar.organization=xpertminds
sonar.projectKey=XpertMinds_Jumentix
sonar.projectName=Jumentix
sonar.sources=apps,packages,ci-cd
sonar.tests=apps/backend-template/test
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/.build/**,**/dist/**,**/.serverless/**,**/coverage/**,**/*.d.ts,apps/service-management/**,**/docker/**,**/AsyncAPIdoc/**,sdk-clients/**,documentation/**,spec/**
sonar.coverage.exclusions=ci-cd/check-fail-closed.js
sonar.cpd.exclusions=apps/backend-template/src/infra/**/*,**/test/**/*
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
