sonar.organization=web2solutions
sonar.projectKey=web2solutions_aaa-typescript-boilerplate

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts,test/**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/.build/**,**/dist/**,**/.serverless/**,**/coverage/**,**/*.d.ts
sonar.cpd.exclusions=src/infra/**/*,test/**/*

# JavaScript/TypeScript coverage report (LCOV)
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
