services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: aaa-dynamodb-local
    command: '-jar DynamoDBLocal.jar -sharedDb'
    ports:
      - '8000:8000'
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data:

