// eslint-disable-next-line no-shadow
export enum EErrorStringCodes {
  INVALID_INPUT = 'GENERIC.INVALID_INPUT',
  NOT_FOUND = 'GENERIC.NOT_FOUND',
  NOT_IMPLEMENTED = 'GENERIC.NOT_IMPLEMENTED',
  UNAUTHORIZED = 'GENERIC.UNAUTHORIZED',
  FORBIDDEN = 'GENERIC.FORBIDDEN',
  CONFLICT = 'GENERIC.CONFLICT',
  RESOURCE_LOCKED = 'GENERIC.RESOURCE_LOCKED',
  INTERNAL_SERVER_ERROR = 'GENERIC.INTERNAL_SERVER_ERROR',
}

// eslint-disable-next-line no-shadow
export enum EErrorNumberCodes {
  'GENERIC.INVALID_INPUT' = 400,
  'GENERIC.NOT_FOUND' = 404,
  'GENERIC.NOT_IMPLEMENTED' = 501,
  'GENERIC.UNAUTHORIZED' = 401,
  'GENERIC.FORBIDDEN' = 403,
  'GENERIC.CONFLICT' = 409,
  'GENERIC.RESOURCE_LOCKED' = 423,
  'GENERIC.INTERNAL_SERVER_ERROR' = 500,
}
