export type { IUser } from '@src/modules/Users/domain/Entity/IUser';
export type { IOrganization } from '@src/modules/Users/domain/Entity/IOrganization';
export { default as User } from '@src/modules/Users/domain/Model/User';
export { default as Organization } from '@src/modules/Users/domain/Model/Organization';
export { UserDataRepository } from '@src/modules/Users/adapters/out/persistence/UserDataRepository';
export { default as OrganizationDataRepository } from '@src/modules/Users/adapters/out/persistence/OrganizationDataRepository';
export { default as UserService } from '@src/modules/Users/service/UserService';
export { default as OrganizationService } from '@src/modules/Users/service/OrganizationService';
export { default as composeUsersAuthServices } from '@src/modules/Users/composition/composeUsersAuthServices';
export { default as UserUseCases } from '@src/modules/Users/application/use-cases/UserUseCases';
export { default as OrganizationUseCases } from '@src/modules/Users/application/use-cases/OrganizationUseCases';
export { default as AuthUseCases } from '@src/modules/Users/application/use-cases/AuthUseCases';

export { default as UserController } from '@src/modules/Users/adapters/in/http/controllers/UserController';
export { default as AuthController } from '@src/modules/Users/adapters/in/http/controllers/AuthController';
export { default as OrganizationController } from '@src/modules/Users/adapters/in/http/controllers/OrganizationController';
export { default as UserHttpController } from '@src/modules/Users/adapters/in/http/controllers/UserController';
export { default as AuthHttpController } from '@src/modules/Users/adapters/in/http/controllers/AuthController';
export { default as OrganizationHttpController } from '@src/modules/Users/adapters/in/http/controllers/OrganizationController';
export { default as AuthService } from '@src/modules/Users/service/AuthService';
export { default as UserProviderLocal } from '@src/modules/Users/service/UserProviderLocal';

// dtos
export type { RequestCreateDocument } from '@src/modules/Users/interface/dto/RequestCreateDocument';
export type { RequestCreateAddress } from '@src/modules/Users/interface/dto/RequestCreateAddress';
export type { RequestCreateEmail } from '@src/modules/Users/interface/dto/RequestCreateEmail';
export type { RequestCreatePhone } from '@src/modules/Users/interface/dto/RequestCreatePhone';
export type { RequestCreateUser } from '@src/modules/Users/interface/dto/RequestCreateUser';
export type { RequestCreateOrganization } from '@src/modules/Users/interface/dto/RequestCreateOrganization';
export type { RequestUpdateDocument } from '@src/modules/Users/interface/dto/RequestUpdateDocument';
export type { RequestUpdateAddress } from '@src/modules/Users/interface/dto/RequestUpdateAddress';
export type { RequestUpdateEmail } from '@src/modules/Users/interface/dto/RequestUpdateEmail';
export type { RequestUpdatePassword } from '@src/modules/Users/interface/dto/RequestUpdatePassword';
export type { RequestUpdatePhone } from '@src/modules/Users/interface/dto/RequestUpdatePhone';
export type { RequestUpdateUser } from '@src/modules/Users/interface/dto/RequestUpdateUser';
export type { RequestUpdateOrganization } from '@src/modules/Users/interface/dto/RequestUpdateOrganization';

export type { ILoginRequest } from '@src/modules/Users/interface/dto/ILoginRequest';
export type { ILogoutRequest } from '@src/modules/Users/interface/dto/ILogoutRequest';
export type { IRegisterRequest } from '@src/modules/Users/interface/dto/IRegisterRequest';
export type { IUpdatePasswordRequest } from '@src/modules/Users/interface/dto/IUpdatePasswordRequest';

export { default as getAllUsers } from '@src/modules/Users/features/getAllUsers';
export { default as createUser } from '@src/modules/Users/features/createUser';
export { default as updateUser } from '@src/modules/Users/features/updateUser';
export { default as getUserById } from '@src/modules/Users/features/getUserById';
export { default as deleteUserById } from '@src/modules/Users/features/deleteUserById';
export { default as updatePassword } from '@src/modules/Users/features/updatePassword';
export { default as createDocument } from '@src/modules/Users/features/createDocument';
export { default as updateDocument } from '@src/modules/Users/features/updateDocument';
export { default as deleteDocument } from '@src/modules/Users/features/deleteDocument';
export { default as createPhone } from '@src/modules/Users/features/createPhone';
export { default as updatePhone } from '@src/modules/Users/features/updatePhone';
export { default as deletePhone } from '@src/modules/Users/features/deletePhone';
export { default as createEmail } from '@src/modules/Users/features/createEmail';
export { default as updateEmail } from '@src/modules/Users/features/updateEmail';
export { default as deleteEmail } from '@src/modules/Users/features/deleteEmail';

export type { IAuthService } from '@src/modules/Users/service/ports/IAuthService';
export type { IAuthSchema } from '@src/modules/Users/service/ports/IAuthSchema';
export { default as EAuthSchemaType } from '@src/modules/Users/service/ports/EAuthSchemaType';
export type { IUserProvider } from '@src/modules/Users/service/ports/IUserProvider';
export type { IUserRepository } from '@src/modules/Users/service/ports/IUserRepository';
export type { IOrganizationRepository } from '@src/modules/Users/service/ports/IOrganizationRepository';
export type { IAuthorizationHeader } from '@src/modules/Users/service/ports/IAuthorizationHeader';
export type { ITokenObject } from '@src/modules/Users/service/ports/ITokenObject';
export type { IUserUseCases } from '@src/modules/Users/application/ports/IUserUseCases';
export type { IOrganizationUseCases } from '@src/modules/Users/application/ports/IOrganizationUseCases';
export type { IAuthUseCases } from '@src/modules/Users/application/ports/IAuthUseCases';
export { default as UserApplicationUseCases } from '@src/modules/Users/application/use-cases/UserUseCases';
export { default as OrganizationApplicationUseCases } from '@src/modules/Users/application/use-cases/OrganizationUseCases';
export { default as AuthApplicationUseCases } from '@src/modules/Users/application/use-cases/AuthUseCases';
export { EUserRole, ROLE_SCOPE_MATRIX } from '@src/modules/Users/domain/security/Rbac';

// events
export { default as UserCreateRequestEvent } from '@src/modules/Users/events/UserCreateRequestEvent';
export { default as UserDeleteRequestEvent } from '@src/modules/Users/events/UserDeleteRequestEvent';
export { default as UserDocumentCreateRequestEvent } from '@src/modules/Users/events/UserDocumentCreateRequestEvent';
export { default as UserDocumentDeleteRequestEvent } from '@src/modules/Users/events/UserDocumentDeleteRequestEvent';
export { default as UserDocumentUpdateRequestEvent } from '@src/modules/Users/events/UserDocumentUpdateRequestEvent';
export { default as UserEmailCreateRequestEvent } from '@src/modules/Users/events/UserEmailCreateRequestEvent';
export { default as UserEmailDeleteRequestEvent } from '@src/modules/Users/events/UserEmailDeleteRequestEvent';
export { default as UserEmailUpdateRequestEvent } from '@src/modules/Users/events/UserEmailUpdateRequestEvent';
export { default as UserGetAllRequestEvent } from '@src/modules/Users/events/UserGetAllRequestEvent';
export { default as UserGetOneRequestEvent } from '@src/modules/Users/events/UserGetOneRequestEvent';
export { default as UserPasswordUpdateRequestEvent } from '@src/modules/Users/events/UserPasswordUpdateRequestEvent';
export { default as UserPhoneCreateRequestEvent } from '@src/modules/Users/events/UserPhoneCreateRequestEvent';
export { default as UserPhoneDeleteRequestEvent } from '@src/modules/Users/events/UserPhoneDeleteRequestEvent';
export { default as UserPhoneUpdateRequestEvent } from '@src/modules/Users/events/UserPhoneUpdateRequestEvent';
export { default as UserUpdateRequestEvent } from '@src/modules/Users/events/UserUpdateRequestEvent';

export { default as LoginRequestEvent } from '@src/modules/Users/events/LoginRequestEvent';
export { default as LogoutRequestEvent } from '@src/modules/Users/events/LogoutRequestEvent';
export { default as RegisterRequestEvent } from '@src/modules/Users/events/RegisterRequestEvent';
export { default as UpdatePasswordRequestEvent } from '@src/modules/Users/events/UpdatePasswordRequestEvent';
export { default as OrganizationCreateRequestEvent } from '@src/modules/Users/events/OrganizationCreateRequestEvent';
export { default as OrganizationGetAllRequestEvent } from '@src/modules/Users/events/OrganizationGetAllRequestEvent';
export { default as OrganizationGetOneRequestEvent } from '@src/modules/Users/events/OrganizationGetOneRequestEvent';
export { default as OrganizationUpdateRequestEvent } from '@src/modules/Users/events/OrganizationUpdateRequestEvent';
export { default as OrganizationDeleteRequestEvent } from '@src/modules/Users/events/OrganizationDeleteRequestEvent';
export { default as OrganizationAddressCreateRequestEvent } from '@src/modules/Users/events/OrganizationAddressCreateRequestEvent';
export { default as OrganizationAddressUpdateRequestEvent } from '@src/modules/Users/events/OrganizationAddressUpdateRequestEvent';
export { default as OrganizationAddressDeleteRequestEvent } from '@src/modules/Users/events/OrganizationAddressDeleteRequestEvent';
export { default as OrganizationPhoneCreateRequestEvent } from '@src/modules/Users/events/OrganizationPhoneCreateRequestEvent';
export { default as OrganizationPhoneUpdateRequestEvent } from '@src/modules/Users/events/OrganizationPhoneUpdateRequestEvent';
export { default as OrganizationPhoneDeleteRequestEvent } from '@src/modules/Users/events/OrganizationPhoneDeleteRequestEvent';
export { default as OrganizationEmailCreateRequestEvent } from '@src/modules/Users/events/OrganizationEmailCreateRequestEvent';
export { default as OrganizationEmailUpdateRequestEvent } from '@src/modules/Users/events/OrganizationEmailUpdateRequestEvent';
export { default as OrganizationEmailDeleteRequestEvent } from '@src/modules/Users/events/OrganizationEmailDeleteRequestEvent';
export { UserIntegrationEventName } from '@src/modules/Users/events/contracts/UserIntegrationEventName';
export { default as UserMessageContracts } from '@src/modules/Users/events/contracts/UserMessageContracts';
export type { IUserEventListeners } from '@src/modules/Users/events/contracts/IUserEventListeners';
export { default as registerUserEventListeners } from '@src/modules/Users/events/listeners/registerUserEventListeners';
export { default as registerUserMessageHandlers } from '@src/modules/Users/events/listeners/registerUserMessageHandlers';
