/**
 * Schema validation and application (JUM-404).
 *
 * Key handling is the least visible and most divergent part of IndexedDB, and it
 * is exactly where a from-scratch engine drifts without anyone noticing. The
 * validator here rejects, up front and with a readable message, the combinations
 * the browser would otherwise reject later from somewhere much less obvious.
 *
 * The three that actually bite:
 *
 * 1. **`multiEntry` with a compound `keyPath`.** IndexedDB forbids it. Left
 *    unchecked, the browser throws `InvalidAccessError` from inside a
 *    `versionchange` transaction, which surfaces as a failed upgrade rather than
 *    as "your schema is wrong".
 * 2. **`autoIncrement` with an outbound key, then supplying a key anyway.** Legal
 *    at schema level, contradictory at call level. Caught in the write path, but
 *    the schema records which shape a store uses so the check is possible at all.
 * 3. **An empty compound `keyPath`.** Accepted by some implementations, rejected
 *    by others. Rejected here so behaviour does not depend on the browser.
 */

import type {
  CanaIndexSchema, CanaKeyPath, CanaSchema, CanaStoreSchema
} from '../contracts';
import { canaError } from './errors';

/** How a store's primary key is supplied. */
export type KeyStrategy =
  /** Key lives inside the record, at `keyPath`. */
  | 'inbound'
  /** Key is supplied by the caller alongside the record. */
  | 'outbound'
  /** Key is generated by the store. */
  | 'generated-outbound'
  /** Key lives inside the record and is generated when absent. */
  | 'generated-inbound';

export function keyStrategyOf(store: CanaStoreSchema): KeyStrategy {
  if (store.keyPath !== undefined) {
    return store.autoIncrement ? 'generated-inbound' : 'inbound';
  }
  return store.autoIncrement ? 'generated-outbound' : 'outbound';
}

function isCompound(keyPath: CanaKeyPath): keyPath is readonly string[] {
  return Array.isArray(keyPath);
}

function validateKeyPath(keyPath: CanaKeyPath, where: string, problems: string[]): void {
  if (isCompound(keyPath)) {
    if (keyPath.length === 0) {
      problems.push(`${where}: compound keyPath is empty; some browsers accept this and others reject it`);
    }
    for (const segment of keyPath) {
      if (typeof segment !== 'string' || segment.length === 0) {
        problems.push(`${where}: compound keyPath contains an empty segment`);
      }
    }
    return;
  }
  if (typeof keyPath !== 'string' || keyPath.length === 0) {
    problems.push(`${where}: keyPath must be a non-empty string or an array of them`);
  }
}

function validateIndex(store: string, index: CanaIndexSchema, problems: string[]): void {
  const where = `store "${store}" index "${index.name}"`;

  if (!index.name) {
    problems.push(`store "${store}": an index has no name`);
  }

  validateKeyPath(index.keyPath, where, problems);

  if (index.multiEntry && isCompound(index.keyPath)) {
    // The rule IndexedDB enforces from inside a versionchange transaction, where
    // the failure reads as a broken upgrade rather than a bad schema.
    problems.push(
      `${where}: multiEntry cannot be combined with a compound keyPath — IndexedDB rejects it`
    );
  }
}

/**
 * Validate a schema before any database is touched.
 *
 * @returns the problems found; empty means the schema is applicable.
 */
export function validateSchema(schema: CanaSchema): readonly string[] {
  const problems: string[] = [];

  if (!Number.isInteger(schema.version) || schema.version < 1) {
    problems.push(`version must be a positive integer, received ${String(schema.version)}`);
  }

  if (schema.stores.length === 0) {
    problems.push('schema declares no stores');
  }

  const seenStores = new Set<string>();
  for (const store of schema.stores) {
    if (!store.name) {
      // Nothing further can be said about a store with no name: every remaining
      // check quotes it, and the messages would be unreadable.
      problems.push('a store has no name');
    } else {
      if (seenStores.has(store.name)) {
        problems.push(`store "${store.name}" is declared more than once`);
      }
      seenStores.add(store.name);

      if (store.keyPath !== undefined) {
        validateKeyPath(store.keyPath, `store "${store.name}"`, problems);
      }

      const seenIndexes = new Set<string>();
      for (const index of store.indexes ?? []) {
        if (seenIndexes.has(index.name)) {
          problems.push(`store "${store.name}": index "${index.name}" is declared more than once`);
        }
        seenIndexes.add(index.name);
        validateIndex(store.name, index, problems);
      }
    }
  }

  return problems;
}

/** Throw a typed failure when a schema is not applicable. */
export function assertSchema(schema: CanaSchema): void {
  const problems = validateSchema(schema);
  if (problems.length > 0) {
    throw canaError(
      'InvalidRequest',
      `Schema is not applicable:\n  - ${problems.join('\n  - ')}`
    );
  }
}

/**
 * Apply a schema inside a `versionchange` transaction.
 *
 * Deliberately additive-and-corrective rather than destructive: stores present in
 * the database but absent from the schema are **left alone**, not dropped.
 *
 * That is a real decision, not an omission. `deleteObjectStore` destroys user
 * data irreversibly, and doing it automatically because a store disappeared from
 * a schema literal means a typo silently deletes a table. Removals are therefore
 * an explicit migration step, never an inference.
 */
/** The `keyPath` shape `createObjectStore` accepts: mutable, or null for outbound. */
function domKeyPath(keyPath: CanaKeyPath | undefined): string | string[] | null {
  if (keyPath === undefined) return null;
  return isCompound(keyPath) ? [...keyPath] : keyPath;
}

export function applySchema(
  database: IDBDatabase,
  transaction: IDBTransaction,
  schema: CanaSchema
): void {
  for (const store of schema.stores) {
    const exists = database.objectStoreNames.contains(store.name);

    const objectStore = exists
      ? transaction.objectStore(store.name)
      : database.createObjectStore(store.name, {
        keyPath: domKeyPath(store.keyPath),
        autoIncrement: store.autoIncrement ?? false
      });

    const existingIndexes = new Set(Array.from(objectStore.indexNames));

    // Index definitions cannot be altered in place. Recreating one would rebuild
    // it over the whole store, which on a large table is a long blocking
    // operation inside an upgrade — so an index that already exists is left as
    // it is, and a changed definition is a migration the author must write
    // rather than something applied silently here.
    const missing = (store.indexes ?? []).filter((index) => !existingIndexes.has(index.name));

    for (const index of missing) {
      objectStore.createIndex(
        index.name,
        domKeyPath(index.keyPath) as string | string[],
        { unique: index.unique ?? false, multiEntry: index.multiEntry ?? false }
      );
    }
  }
}
