version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

jobs:
  test-source:
    docker:
      - image: cimg/node:22.23
      - image: redis:latest
        environment:
          REDIS_ARGS: "--sysctl vm.overcommit_memory=1"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
            - pnpm-store-v1-{{ .Branch }}
      - run:
          name: setup pnpm
          command: npm install -g pnpm@9.15.3
      - run:
          name: install packages
          command: pnpm install --no-frozen-lockfile
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - save_cache:
          key: pnpm-store-v1-{{ .Branch }}
          paths:
            - ~/.pnpm-store
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Run Tests
          command: npm run ci:monorepo
      - codecov/upload

workflows:
  test-source:
    jobs:
      - test-source
