export default {
  index: { title: 'Pacotes do workspace Jumentix', display: 'hidden' },
  'adapter-runtime-bootstrap': '@jumentix/adapter-runtime-bootstrap',
  'cli-init': '@jumentix/cli-init',
  'config-eslint': '@jumentix/config-eslint',
  'config-jest': '@jumentix/config-jest',
  'config-ts': '@jumentix/config-ts',
  'database-client-factory': '@jumentix/database-client-factory',
  'external-db-repositories': '@jumentix/external-db-repositories',
  'external-persistence-core': '@jumentix/external-persistence-core',
  'external-store-proxy': '@jumentix/external-store-proxy',
  'persistence-contracts': '@jumentix/persistence-contracts',
  'runtime-infra': '@jumentix/runtime-infra',
  'sdk-grpc-client': '@jumentix/sdk-grpc-client',
  'sdk-rest-client': '@jumentix/sdk-rest-client',
  'sdk-websocket-client': '@jumentix/sdk-websocket-client',
  'shared-contracts': '@jumentix/shared-contracts',
  cana: '@jumentix/cana',
  'designer-core': '@jumentix/designer-core',
  'key-value-storage': '@jumentix/key-value-storage',
  'mutex-service': '@jumentix/mutex-service',
  'message-mediator': '@jumentix/message-mediator'
};
