name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.operating-system }}
    
    strategy:
      matrix:
        node-version: [10.x, 11.x]
        #operating-system: [ubuntu-latest, windows-latest]
    
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
      redis:
        image: redis
        ports:
        - 6379/tcp
        options: --entrypoint redis-server
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run mongo
      run: sudo docker run --name mongo -d -p 27017:27017 mongo
    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 7.6.0
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        sleep 10 && export NODE_ENV=CI && node_modules/.bin/nodemon /home/circleci/Jumentix/dist/app.js
      env:
        CI: true
