const HTTP_PORT = 3000;
const DOCS_PREFIX = '/docs';
const API_PREFIX = '/api';

const MINUTES_IN_THE_FUTURE = 5;

const VALIDATION_ERROR_NAME = 'validation_error';
const LOCKED_RESOURCE_ERROR_NAME = 'locked_resource';
const FORBIDDEN_ERROR_NAME = 'forbidden';
const UNAUTHORIZED_ERROR_NAME = 'unauthorized';
const NOT_FOUND_ERROR_NAME = 'not_found';
const INTERNAL_SERVER_ERROR = 'internal_server_error';
const DOMAIN_VALIDATION_ERROR_NAME = 'domain_validation_error';
const DOMAIN_NOT_FOUND_ERROR_NAME = 'domain_not_found';
const EVENT_INVALID_MESSAGE = 'event_invalid_message';
const INFRA_NOT_IMPLEMENTED = 'infrastructure_not_implemented';
const DATABASE_NOT_FOUND_ERROR_NAME = 'database_not_found';
const DATABASE_CONFLICT_ERROR_NAME = 'database_duplicated';
const DATABASE_PAGING_ERROR = 'database_paging_error';

const DEFAULT_PAGE_SIZE = 30;

const BCRYPT_SALT_ROUNDS = 10;

const PASSWORD_MIN_LENGTH = 8;

const KV_KEY_NAME_PREFIX = 'my_prefix';
const MUTEX_KEY_NAME_PREFIX = 'mutex';

export {
  API_PREFIX,
  BCRYPT_SALT_ROUNDS,
  DATABASE_CONFLICT_ERROR_NAME,
  DATABASE_NOT_FOUND_ERROR_NAME,
  DATABASE_PAGING_ERROR,
  DEFAULT_PAGE_SIZE,
  DOCS_PREFIX,
  DOMAIN_NOT_FOUND_ERROR_NAME,
  DOMAIN_VALIDATION_ERROR_NAME,
  EVENT_INVALID_MESSAGE,
  FORBIDDEN_ERROR_NAME,
  HTTP_PORT,
  INFRA_NOT_IMPLEMENTED,
  INTERNAL_SERVER_ERROR,
  KV_KEY_NAME_PREFIX,
  LOCKED_RESOURCE_ERROR_NAME,
  MINUTES_IN_THE_FUTURE,
  MUTEX_KEY_NAME_PREFIX,
  NOT_FOUND_ERROR_NAME,
  PASSWORD_MIN_LENGTH,
  UNAUTHORIZED_ERROR_NAME,
  VALIDATION_ERROR_NAME
};

// Legacy underscored aliases kept for consumers outside this app
// (service-management-api, cli-init templates) that still import them.
export {
  API_PREFIX as _API_PREFIX_,
  BCRYPT_SALT_ROUNDS as _BCRYPT_SALT_ROUNDS_,
  DATABASE_CONFLICT_ERROR_NAME as _DATABASE_CONFLICT_ERROR_NAME_,
  DATABASE_NOT_FOUND_ERROR_NAME as _DATABASE_NOT_FOUND_ERROR_NAME_,
  DATABASE_PAGING_ERROR as _DATABASE_PAGING_ERROR_,
  DEFAULT_PAGE_SIZE as _DEFAULT_PAGE_SIZE_,
  DOCS_PREFIX as _DOCS_PREFIX_,
  DOMAIN_NOT_FOUND_ERROR_NAME as _DOMAIN_NOT_FOUND_ERROR_NAME_,
  DOMAIN_VALIDATION_ERROR_NAME as _DOMAIN_VALIDATION_ERROR_NAME_,
  EVENT_INVALID_MESSAGE as _EVENT_INVALID_MESSAGE_,
  FORBIDDEN_ERROR_NAME as _FORBIDDEN_ERROR_NAME_,
  HTTP_PORT as _HTTP_PORT_,
  INFRA_NOT_IMPLEMENTED as _INFRA_NOT_IMPLEMENTED_,
  INTERNAL_SERVER_ERROR as _INTERNAL_SERVER_ERROR_,
  KV_KEY_NAME_PREFIX as _KV_KEY_NAME_PREFIX_,
  LOCKED_RESOURCE_ERROR_NAME as _LOCKED_RESOURCE_ERROR_NAME_,
  MINUTES_IN_THE_FUTURE as _MINUTES_IN_THE_FUTURE_,
  MUTEX_KEY_NAME_PREFIX as _MUTEX_KEY_NAME_PREFIX_,
  NOT_FOUND_ERROR_NAME as _NOT_FOUND_ERROR_NAME_,
  PASSWORD_MIN_LENGTH as _PASSWORD_MIN_LENGTH_,
  UNAUTHORIZED_ERROR_NAME as _UNAUTHORIZED_ERROR_NAME_,
  VALIDATION_ERROR_NAME as _VALIDATION_ERROR_NAME_
};
