FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig*.json ./
COPY src ./src
COPY spec ./spec
COPY seed ./seed
COPY ci-cd ./ci-cd
RUN npm run build:dev

EXPOSE 3000

CMD ["npm", "run", "prod:fastify"]
